"""add file_path to course_resources

Revision ID: 1841715c8ca7
Revises: 60c266929e14
Create Date: 2025-05-20 22:23:51.048421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1841715c8ca7'
down_revision = '60c266929e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_resources', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
