"""add files field to assignment submissions

Revision ID: befda8192a76
Revises: 1841715c8ca7
Create Date: 2025-05-20 22:52:03.661772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'befda8192a76'
down_revision = '1841715c8ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('files', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment_submissions', schema=None) as batch_op:
        batch_op.drop_column('files')

    # ### end Alembic commands ###
